### ISSUE TITLE
Preview markdown in Github.md using a keyboard shortcut

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/javascripts#2]
Adding a keyboard shortcut for refreshing the markdown preview will make the user experience more convenient.  Right now, user is forced to move their mouse and click on the "Refresh" button. 
See http://gmd.aavi.me/ for the deployed site.

The source of github.md is in github.md folder. https://github.com/aviaryan/javascripts/tree/gh-pages/github.md

**Comment by BhaveshSGupta** [comment]
I can take this, Which key do you think would be best for this?

**Comment by aviaryan** [comment]
@BhaveshSGupta Thanks for your interest.
Ctrl + Shift + P would be nice. 
Even Github uses it for previewing comments in issues.

**Comment by BhaveshSGupta** [comment]
@aviaryan hey I was thinking of using this https://github.com/jeresig/jquery.hotkeys, to ensure browser compatibility! Do you have anyother work around in your mind?

**Comment by aviaryan** [comment]
@BhaveshSGupta Looks good :star2:
